# """
# Django settings for brain project.

# Generated by 'django-admin startproject' using Django 5.1.4.

# For more information on this file, see
# https://docs.djangoproject.com/en/5.1/topics/settings/

# For the full list of settings and their values, see
# https://docs.djangoproject.com/en/5.1/ref/settings/
# """

# from pathlib import Path, os

# # Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR = Path(__file__).resolve().parent.parent


# # Quick-start development settings - unsuitable for production
# # See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# # SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure-=+tficroe&rwn()9*^)tg5dhs!(+s1(jto7c@e9@*59(skh097'

# # SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True

# # ALLOWED_HOSTS = ['127.0.0.1', 'localhost', "https://ten-brain.onrender.com"]  # Add additional hosts as needed.
# # ALLOWED_HOSTS = ['127.0.0.1', 'localhost', "https://ten-brain-8ep5.onrender.com"] 
# ALLOWED_HOSTS = ['127.0.0.1', 'localhost', 'ten-brain-8ep5.onrender.com']


# # Email settings
# EMAIL_HOST = "smtp.gmail.com"  # smtp=simple mail transfer protocol
# EMAIL_HOST_USER = "debadritapaul76@gmail.com"  # sender
# EMAIL_HOST_PASSWORD = "vgtuivjbzirejlcz"
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"

# # Application definition

# INSTALLED_APPS = [
#     'django.contrib.admin',
#     'django.contrib.auth',
#     'django.contrib.contenttypes',
#     'django.contrib.sessions',
#     'django.contrib.messages',
#     'django.contrib.staticfiles',
#     'brain_app',
#     'django_summernote',
# ]

# MIDDLEWARE = [
#     'django.middleware.security.SecurityMiddleware',
#     'django.contrib.sessions.middleware.SessionMiddleware',
#     'django.middleware.common.CommonMiddleware',
#     'django.middleware.csrf.CsrfViewMiddleware',
#     'django.contrib.auth.middleware.AuthenticationMiddleware',
#     'django.contrib.messages.middleware.MessageMiddleware',
#     'django.middleware.clickjacking.XFrameOptionsMiddleware',
# ]

# ROOT_URLCONF = 'brain.urls'

# TEMPLATES = [
#     {
#         'BACKEND': 'django.template.backends.django.DjangoTemplates',
#         'DIRS': [os.path.join(BASE_DIR, 'templates')],
#         'APP_DIRS': True,
#         'OPTIONS': {
#             'context_processors': [
#                 'django.template.context_processors.debug',
#                 'django.template.context_processors.request',
#                 'django.contrib.auth.context_processors.auth',
#                 'django.contrib.messages.context_processors.messages',
#             ],
#         },
#     },
# ]

# WSGI_APPLICATION = 'brain.wsgi.application'


# # Database
# # https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# DATABASES = {
#     'default': {
#         # 'ENGINE': 'django.db.backends.postgresql',
#         # 'NAME': 'ten_brain',
#         # 'HOST': 'localhost',
#         # 'USER': 'ten_brain_user',
#         # 'PASSWORD': 'Wc0hJ38CXupJfb2yfGMrSbkQusElvZG5',
#         # 'PORT': '5432',
# 'ENGINE': 'django.db.backends.postgresql',
#         'NAME': os.environ.get('DB_NAME'),  # Replace with your database name
#         'USER': os.environ.get('DB_USER'),  # Replace with your database user
#         'PASSWORD': os.environ.get('DB_PASSWORD'),  # Replace with your database password
#         'HOST': os.environ.get('DB_HOST', 'localhost'),  # Database host
#         'PORT': os.environ.get('DB_PORT', '5432'),  # Database port  
#     }
# }
# # DATABASES = {
# #     'default': {
# #         'ENGINE': 'django.db.backends.sqlite3',
# #         'NAME': BASE_DIR / 'db.sqlite3',
# #     }
# # }


# # Password validation
# # https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

# AUTH_PASSWORD_VALIDATORS = [
#     {
#         'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
#     },
# ]


# # Internationalization
# # https://docs.djangoproject.com/en/5.1/topics/i18n/

# LANGUAGE_CODE = 'en-us'

# TIME_ZONE = 'UTC'

# USE_I18N = True

# USE_TZ = True


# # Static files (CSS, JavaScript, Images)
# # https://docs.djangoproject.com/en/5.1/howto/static-files/

# STATIC_URL = 'static/'
# STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
# MEDIA_URL = '/media/'
# MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# # Default primary key field type
# # https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

# DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# PORT = os.environ.get('PORT', '8000')

# # """
# # Django settings for brain project.

# # Generated by 'django-admin startproject' using Django 5.1.4.

# # For more information on this file, see
# # https://docs.djangoproject.com/en/5.1/topics/settings/

# # For the full list of settings and their values, see
# # https://docs.djangoproject.com/en/5.1/ref/settings/
# # """

# # from pathlib import Path,os

# # # Build paths inside the project like this: BASE_DIR / 'subdir'.
# # BASE_DIR = Path(__file__).resolve().parent.parent


# # # Quick-start development settings - unsuitable for production
# # # See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# # # SECURITY WARNING: keep the secret key used in production secret!
# # SECRET_KEY = 'django-insecure-=+tficroe&rwn()9*^)tg5dhs!(+s1(jto7c@e9@*59(skh097'

# # # SECURITY WARNING: don't run with debug turned on in production!
# # DEBUG = True

# # ALLOWED_HOSTS = []

# # #Email settings
# # EMAIL_HOST="smtp.gmail.com" #smtp=simple mail transfer protocol
# # EMAIL_HOST_USER="debadritapaul76@gmail.com" #sender
# # EMAIL_HOST_PASSWORD="vgtuivjbzirejlcz"
# # EMAIL_PORT=587
# # EMAIL_USE_TLS=True
# # EMAIL_BACKEND="django.core.mail.backends.smtp.EmailBackend"

# # # Application definition

# # INSTALLED_APPS = [
# #     'django.contrib.admin',
# #     'django.contrib.auth',
# #     'django.contrib.contenttypes',
# #     'django.contrib.sessions',
# #     'django.contrib.messages',
# #     'django.contrib.staticfiles',
# #     'brain_app',
# #     'django_summernote',

# # ]

# # MIDDLEWARE = [
# #     'django.middleware.security.SecurityMiddleware',
# #     'django.contrib.sessions.middleware.SessionMiddleware',
# #     'django.middleware.common.CommonMiddleware',
# #     'django.middleware.csrf.CsrfViewMiddleware',
# #     'django.contrib.auth.middleware.AuthenticationMiddleware',
# #     'django.contrib.messages.middleware.MessageMiddleware',
# #     'django.middleware.clickjacking.XFrameOptionsMiddleware',
# # ]

# # ROOT_URLCONF = 'brain.urls'

# # TEMPLATES = [
# #     {
# #         'BACKEND': 'django.template.backends.django.DjangoTemplates',
# #         'DIRS': [os.path.join(BASE_DIR,'templates')],
# #         'APP_DIRS': True,
# #         'OPTIONS': {
# #             'context_processors': [
# #                 'django.template.context_processors.debug',
# #                 'django.template.context_processors.request',
# #                 'django.contrib.auth.context_processors.auth',
# #                 'django.contrib.messages.context_processors.messages',
# #             ],
# #         },
# #     },
# # ]

# # WSGI_APPLICATION = 'brain.wsgi.application'


# # # Database
# # # https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# # DATABASES = {
# #     'default': {
# #         'ENGINE': 'django.db.backends.mysql',
# #         'NAME': 'ten_brain_research',
# #         'HOST': 'localhost',
# #         'USER': 'root',
# #         'PASSWORD': 'root',
# #         'PORT': '3306',
# #     }
# # }
# # # DATABASES = {
# # #     'default': {
# # #         'ENGINE': 'django.db.backends.sqlite3',
# # #         'NAME': BASE_DIR / 'db.sqlite3',
# # #     }
# # # }


# # # Password validation
# # # https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

# # AUTH_PASSWORD_VALIDATORS = [
# #     {
# #         'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
# #     },
# #     {
# #         'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
# #     },
# #     {
# #         'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
# #     },
# #     {
# #         'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
# #     },
# # ]


# # # Internationalization
# # # https://docs.djangoproject.com/en/5.1/topics/i18n/

# # LANGUAGE_CODE = 'en-us'

# # TIME_ZONE = 'UTC'

# # USE_I18N = True

# # USE_TZ = True


# # # Static files (CSS, JavaScript, Images)
# # # https://docs.djangoproject.com/en/5.1/howto/static-files/

# # STATIC_URL = 'static/'
# # STATICFILES_DIRS = [os.path.join(BASE_DIR,'static')]
# # MEDIA_URL='/media/'
# # MEDIA_ROOT=os.path.join(BASE_DIR,'media')

# # # Default primary key field type
# # # https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

# # DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'







from pathlib import Path
import os  # Ensure that os is imported

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-=+tficroe&rwn()9*^)tg5dhs!(+s1(jto7c@e9@*59(skh097'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', 'localhost', 'ten-brain-8ep5.onrender.com']  # Update to match your domain

# Email settings
EMAIL_HOST = "smtp.gmail.com"
EMAIL_HOST_USER = "debadritapaul76@gmail.com"
EMAIL_HOST_PASSWORD = "vgtuivjbzirejlcz"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'brain_app',
    'django_summernote',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'brain.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'brain.wsgi.application'

# Database settings
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DB_NAME', 'ten_brain'),  # Fallback to 'ten_brain'
        'USER': os.environ.get('DB_USER', 'ten_brain_user'),  # Fallback to 'ten_brain_user'
        'PASSWORD': os.environ.get('DB_PASSWORD', 'default_password'),  # Use a secure default
        'HOST': os.environ.get('DB_HOST', 'localhost'),  # Fallback to localhost
        'PORT': os.environ.get('DB_PORT', '5432'),  # Fallback to 5432
    }
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization settings
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static and media settings
STATIC_URL = 'static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Set the port if required (usually automatically handled in Render)
PORT = os.environ.get('PORT', '8000')

